<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ins_Systems_iCheck-helper</name>
   <tag></tag>
   <elementGuidId>90916419-5a82-4329-bd6b-8cfda40aa894</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.icheckbox_square-blue.hover > ins.iCheck-helper</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='page-wrapper']/div[2]/div/form/div/div/div[2]/div/div[3]/div[2]/div/div/label/div/ins</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>ins</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>iCheck-helper</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page-wrapper&quot;)/div[@class=&quot;main-content ng-scope&quot;]/div[@class=&quot;usmle-create-test ng-scope&quot;]/form[@class=&quot;ng-valid-maxlength ng-valid-integer ng-dirty ng-valid-parse ng-valid ng-valid-required&quot;]/div[@class=&quot;wrapper wrapper-content row animated fadeInRight&quot;]/div[@class=&quot;col-xs-12&quot;]/div[@class=&quot;row&quot;]/div[1]/div[3]/div[@class=&quot;ibox float-e-margins&quot;]/div[@class=&quot;ibox-title&quot;]/div[@class=&quot;pull-left header introQuestionsStep4&quot;]/label[@class=&quot;hover&quot;]/div[@class=&quot;icheckbox_square-blue hover&quot;]/ins[@class=&quot;iCheck-helper&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page-wrapper']/div[2]/div/form/div/div/div[2]/div/div[3]/div[2]/div/div/label/div/ins</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div/label/div/ins</value>
   </webElementXpaths>
</WebElementEntity>
